import RPi.GPIO as GPIO 
import time 

def main():

    GPIO.setmode(GPIO.BCM)
    GPIO.setwarnings(False)
    GPIO.setup(14,GPIO.OUT)
    GPIO.setup(15,GPIO.OUT)
    GPIO.setup(18,GPIO.OUT)
    GPIO.setup(23,GPIO.OUT)
    GPIO.setup(24,GPIO.OUT)
    GPIO.setup(25,GPIO.OUT)
    GPIO.setup(8,GPIO.OUT)
    GPIO.setup(7,GPIO.OUT)
    GPIO.setup(12,GPIO.OUT)
    GPIO.setup(14,GPIO.OUT)
    GPIO.setup(16,GPIO.OUT)
    GPIO.setup(20,GPIO.OUT)
    GPIO.setup(21,GPIO.OUT)
    GPIO.setup(26,GPIO.OUT)
    GPIO.setup(19,GPIO.OUT)
    GPIO.setup(13,GPIO.OUT)
    GPIO.setup(6,GPIO.OUT)
    GPIO.setup(5,GPIO.OUT)
    GPIO.setup(11,GPIO.OUT)
    GPIO.setup(9,GPIO.OUT)
    GPIO.setup(10,GPIO.OUT)
    GPIO.setup(22,GPIO.OUT)
    GPIO.setup(27,GPIO.OUT)
    GPIO.setup(17,GPIO.OUT)
    GPIO.setup(4,GPIO.OUT)
    GPIO.setup(3,GPIO.OUT)
    GPIO.setup(2,GPIO.OUT)
    GPIO.output(14,0)
    GPIO.output(15,0)
    GPIO.output(18,0)
    GPIO.output(23,0)
    GPIO.output(24,0)
    GPIO.output(25,0)
    GPIO.output(8,0)
    GPIO.output(7,0)
    GPIO.output(12,0)
    GPIO.output(14,0)
    GPIO.output(16,0)
    GPIO.output(20,0)
    GPIO.output(21,0)
    GPIO.output(26,0)
    GPIO.output(19,0)
    GPIO.output(13,0)
    GPIO.output(6,0)
    GPIO.output(5,0)
    GPIO.output(11,0)
    GPIO.output(9,0)
    GPIO.output(10,0)
    GPIO.output(22,0)
    GPIO.output(27,0)
    GPIO.output(17,0)
    GPIO.output(4,0)
    GPIO.output(3,0)
    GPIO.output(2,0)

    GPIO.cleanup() 

main()
